[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; connect-src *; font-src * data:; style-src * 'unsafe-inline'; img-src * data: blob:; script-src * 'unsafe-inline' 'unsafe-eval';"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/blog/*"
  to = "https://blog.bernofco.com/:splat"
  status = 200 