[build]
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://public-api.wordpress.com https://cdn.amplitude.com https://region1.google-analytics.com https://analytics.google.com https://www.google-analytics.com https://cdn.jsdelivr.net https://dd.doubleclick.net; font-src 'self' https://fonts.cdnfonts.com https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.cdnfonts.com; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.amplitude.com https://region1.google-analytics.com https://analytics.google.com https://www.google-analytics.com https://cdn.jsdelivr.net https://dd.doubleclick.net;"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 