export default {
  routes: [
    '/',
    '/blog',
    '/global-services',
    '/startup-development',
    '/vibe-coding',
    '/cookie-policy',
    '/privacy-policy',
    '/terms-of-service',
    '/global-services/ch',
    '/global-services/uk',
    '/global-services/us',
    '/global-services/it',
    '/ch/web-development',
    '/ch/software-development',
    '/ch/startup-development',
    '/uk/web-development',
    '/uk/software-development',
    '/uk/startup-development',
    '/us/web-development',
    '/us/software-development',
    '/us/startup-development',
    '/it/web-development',
    '/it/software-development',
    '/it/startup-development',
  ],
  renderTimeout: 30000,
  script: 'async',
  formatting: 'minify',
  criticalCSS: true,
}
